## Numpy Lab session 
- install numpy 
- import the numpy

In [1]:
import numpy as np

In [2]:
food = np.array(["pakora","samosa","raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
len(food)

3

In [8]:
price[2]

5

In [9]:
food[2]

'raita'

In [10]:
food[0:]

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [12]:
price.mean()

5.0

In [13]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
# empthy
np.empty(5)

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [17]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [20]:
# specific interval
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
# table of 5
np.arange(0,55,5)


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
#line space 
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
#specify your data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1])

In [26]:
np.ones(10,dtype= np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [27]:
a = np.array([10,15,78,8,8,8.9,9.0,6])
a

array([10. , 15. , 78. ,  8. ,  8. ,  8.9,  9. ,  6. ])

In [29]:
a.sort()
a

array([ 6. ,  8. ,  8. ,  8.9,  9. , 10. , 15. , 78. ])

In [30]:
b = np.array([2,3,4,5,6,7,])
b

array([2, 3, 4, 5, 6, 7])

In [35]:
c =  np.concatenate((a,b))
c

array([ 6. ,  8. ,  8. ,  8.9,  9. , 10. , 15. , 78. ,  2. ,  3. ,  4. ,
        5. ,  6. ,  7. ])

In [37]:
c.sort()
c

array([ 2. ,  3. ,  4. ,  5. ,  6. ,  6. ,  7. ,  8. ,  8. ,  8.9,  9. ,
       10. , 15. , 78. ])

# 2D Array

In [39]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [44]:
b = np.array([[2,4,5,6,8],[3,5,6,7,0]])
b

array([[2, 4, 5, 6, 8],
       [3, 5, 6, 7, 0]])

In [46]:
d = np.concatenate((a,b))
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 2,  4,  5,  6,  8],
       [ 3,  5,  6,  7,  0]])

In [47]:
d = np.concatenate((a,b),axis=1)
d

array([[ 1,  2,  3,  4,  5,  2,  4,  5,  6,  8],
       [ 6,  7,  8,  9, 10,  3,  5,  6,  7,  0]])